package com.erp.common.model;

import java.io.Serializable;

import org.apache.ibatis.type.Alias;


@SuppressWarnings("serial")
@Alias("ProductGroup")
public class ProductGroup implements Serializable{
	
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_group.group_id
     *
     * @mbggenerated Thu Feb 18 20:26:36 CST 2016
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product_group.group_name
     *
     * @mbggenerated Thu Feb 18 20:26:36 CST 2016
     */
    private String groupName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_group.group_id
     *
     * @return the value of tb_product_group.group_id
     *
     * @mbggenerated Thu Feb 18 20:26:36 CST 2016
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_group.group_id
     *
     * @param groupId the value for tb_product_group.group_id
     *
     * @mbggenerated Thu Feb 18 20:26:36 CST 2016
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product_group.group_name
     *
     * @return the value of tb_product_group.group_name
     *
     * @mbggenerated Thu Feb 18 20:26:36 CST 2016
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product_group.group_name
     *
     * @param groupName the value for tb_product_group.group_name
     *
     * @mbggenerated Thu Feb 18 20:26:36 CST 2016
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

}
