package com.erp.common.model;

import java.io.Serializable;

import org.apache.ibatis.type.Alias;

@SuppressWarnings("serial")
@Alias("User")
public class User implements Serializable{
	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_id
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_name
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.password
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.email
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.tel_no
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    private String telNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.role
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    private String role;
    
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_id
     *
     * @return the value of tb_user.user_id
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_id
     *
     * @param userId the value for tb_user.user_id
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_name
     *
     * @return the value of tb_user.user_name
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_name
     *
     * @param userName the value for tb_user.user_name
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.password
     *
     * @return the value of tb_user.password
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.password
     *
     * @param password the value for tb_user.password
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.email
     *
     * @return the value of tb_user.email
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.email
     *
     * @param email the value for tb_user.email
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.tel_no
     *
     * @return the value of tb_user.tel_no
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.tel_no
     *
     * @param telNo the value for tb_user.tel_no
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.role
     *
     * @return the value of tb_user.role
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.role
     *
     * @param role the value for tb_user.role
     *
     * @mbggenerated Fri Feb 05 22:09:31 CST 2016
     */
    public void setRole(String role) {
        this.role = role;
    }

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
}
